services:
  db:
    image: postgres:16
    container_name: jgms_db_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: JGMS
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d JGMS"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jgms_api_container
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=JGMS;Username=admin;Password=123456
      - Jwt__Key=THIS_IS_A_SUPER_SECRET_KEY_123456
      - Jwt__Issuer=SWP391_JGMS
      - Jwt__Audience=SWP391_JGMS_USERS
      - Jwt__ExpireMinutes=60
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
